{
  config,
  lib,
  pkgs,
  ...
}: let
  inherit (lib) mkOption mkIf mkEnableOption mkDefault types literalExpression;
  cfg = config.services.llamacpp-server;
  isRouter = cfg.router.enable;

  svcUser = cfg.user;
  svcGroup = cfg.group;

  singleModelArgs =
    lib.optionals (!isRouter)
    (lib.optionals (cfg.model != null) ["-m" cfg.model]
      ++ lib.optionals (cfg.mmproj != null) ["--mmproj" cfg.mmproj]);

  routerArgs = lib.optionals isRouter [
    "--models-preset"
    presetIni
    "--models-max"
    (toString cfg.router.modelsMax)
    "--sleep-idle-seconds"
    (toString cfg.router.sleepIdleSeconds)
  ];

  toolArgs =
    lib.optionals (cfg.tools != []) ["--tools" (lib.concatStringsSep "," cfg.tools)];
  apiKeyArgs =
    lib.optionals (cfg.apiKeyFile != null) ["--api-key-file" cfg.apiKeyFile];

  # Generate the preset INI content from the models attrset
  presetIni = pkgs.writeText "llamacpp-presets.ini" (let
    defaultsSection =
      if cfg.router.defaults == {}
      then ""
      else ''
        [*]
        ${lib.concatStringsSep "\n" (lib.mapAttrsToList (k: v: "${k} = ${v}") cfg.router.defaults)}

      '';
    modelSections =
      lib.mapAttrsToList (name: modelCfg: ''
        [${name}]
        m = ${cfg.router.modelsDir}/${builtins.baseNameOf modelCfg.url}
        ${lib.concatStringsSep "\n" (lib.mapAttrsToList (k: v: "${k} = ${v}") modelCfg.args)}
      '')
      cfg.router.models;
  in
    lib.concatStringsSep "\n" (["# Auto-generated by llamacpp-server module"] ++ lib.optional (defaultsSection != "") defaultsSection ++ modelSections));

  # Generate preStart download script depending on mode
  preStartScript =
    if isRouter
    then
      lib.concatStringsSep "\n" (lib.mapAttrsToList (name: modelCfg: let
          filename = builtins.baseNameOf modelCfg.url;
          dest = "${cfg.router.modelsDir}/${filename}";
        in ''
          if ! [ -f "${dest}" ]; then
            echo "→ ${name}: downloading..."
            mkdir -p "${cfg.router.modelsDir}"
            ${pkgs.curl}/bin/curl -fSL -o "${dest}.tmp" "${modelCfg.url}" --retry 3 --retry-delay 5
            mv "${dest}.tmp" "${dest}"
            echo "✓ ${name}: downloaded"
          fi
        '')
        cfg.router.models)
    else if (cfg.model != null && cfg.modelUrl != null)
    then ''
      if ! [ -f "${cfg.model}" ]; then
        mkdir -p "$(dirname "${cfg.model}")"
        echo "→ downloading model to ${cfg.model}..."
        ${pkgs.curl}/bin/curl -fSL -o "${cfg.model}.tmp" "${cfg.modelUrl}" --retry 3 --retry-delay 5
        mv "${cfg.model}.tmp" "${cfg.model}"
        echo "✓ model downloaded"
      fi
    ''
    else "";
in {
  options.services.llamacpp-server = {
    enable = mkEnableOption "llama-server (llama.cpp) LLM inference server";

    host = mkOption {
      type = types.str;
      default = "127.0.0.1";
      description = "Host address to bind to";
    };

    port = mkOption {
      type = types.port;
      default = 8080;
      description = "Port to listen on";
    };

    model = mkOption {
      type = types.nullOr types.str;
      default = null;
      description = "Path to GGUF model file (auto-downloaded on first start if missing). Mutually exclusive with router.enable.";
    };

    modelUrl = mkOption {
      type = types.nullOr types.str;
      default = null;
      description = "URL to download the model GGUF from when it doesn't exist on disk";
    };

    mmproj = mkOption {
      type = types.nullOr types.str;
      default = null;
      description = "Path to multimodal projector GGUF for vision models";
    };

    extraArgs = mkOption {
      type = types.listOf types.str;
      default = [];
      description = "Extra arguments to pass to llama-server (applied as defaults to child processes in router mode)";
    };

    package = mkOption {
      type = types.package;
      default = pkgs.llama-cpp;
      defaultText = literalExpression "pkgs.llama-cpp";
      description = "llama.cpp package to use";
    };

    apiKeyFile = mkOption {
      type = types.nullOr types.path;
      default = null;
      description = "Path to API key file (one key per line). Enables --api-key-file for tool authentication.";
    };

    tools = mkOption {
      type = types.listOf types.str;
      default = [];
      description = "Built-in tools to enable (e.g., exec_shell_command, read_file, get_datetime). Use with caution — exec_shell_command runs arbitrary commands.";
    };

    user = mkOption {
      type = types.str;
      default = "llamacpp";
      description = "User to run the server as";
    };

    group = mkOption {
      type = types.str;
      default = "llamacpp";
      description = "Group to run the server as";
    };

    router = {
      enable = mkOption {
        type = types.bool;
        default = false;
        description = "Enable multi-model router mode (mutually exclusive with model)";
      };

      modelsDir = mkOption {
        type = types.path;
        default = "/dragon/servers/llamacpp/models";
        description = "Directory containing GGUF model files for the router server";
      };

      models = mkOption {
        type = types.attrsOf (types.submodule {
          options = {
            url = mkOption {
              type = types.str;
              description = "URL to download the model GGUF from";
            };
            args = mkOption {
              type = types.attrsOf types.str;
              default = {};
              description = "Per-model preset arguments (e.g., ctx-size, temp, top-p)";
            };
          };
        });
        default = {};
        description = "Model definitions with download URLs and preset arguments";
      };

      modelsMax = mkOption {
        type = types.int;
        default = 1;
        description = "Maximum number of models to load simultaneously (0 = unlimited)";
      };

      sleepIdleSeconds = mkOption {
        type = types.int;
        default = 300;
        description = "Seconds of idleness after which the server will unload a model (-1 = disabled)";
      };

      defaults = mkOption {
        type = types.attrsOf types.str;
        default = {fa = "on";};
        description = "Default preset arguments applied to all models (the [*] section)";
      };
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = !(isRouter && cfg.model != null);
        message = "llamacpp-server: router.enable and model are mutually exclusive. Set model = null when using router mode.";
      }
    ];

    users.users.${svcUser} = {
      isSystemUser = true;
      group = svcGroup;
      description = "llama.cpp server user";
    };
    users.groups.${svcGroup} = {};

    systemd.services.llamacpp-server =
      {
        description = "llama-server (llama.cpp)";
        wantedBy = ["multi-user.target"];
        after = ["network.target"];
        serviceConfig = {
          ExecStart = lib.concatStringsSep " " (
            [
              "${cfg.package}/bin/llama-server"
              "--host"
              cfg.host
              "--port"
              (toString cfg.port)
            ]
            ++ singleModelArgs
            ++ routerArgs
            ++ toolArgs
            ++ apiKeyArgs
            ++ cfg.extraArgs
          );
          User = svcUser;
          Group = svcGroup;
          Environment = [
            "PATH=${lib.makeSearchPath "bin" (with pkgs; [bash curl coreutils findutils gnugrep gnused systemd python3])}:/run/wrappers/bin"
          ];
          Restart = "always";
          RestartSec = 5;
          TimeoutStartSec = lib.mkDefault "infinity";
          ProtectSystem = "strict";
          ProtectHome = true;
          ReadWritePaths =
            lib.optionals isRouter [cfg.router.modelsDir]
            ++ lib.optionals (cfg.model != null) [(builtins.dirOf cfg.model)];
          PrivateTmp = true;
          NoNewPrivileges = true;
          IPAddressAllow = "127.0.0.0/8";
        };
      }
      // lib.optionalAttrs (preStartScript != "") {
        preStart = lib.mkBefore preStartScript;
      };

    system.activationScripts.llamacpp-models-dir = lib.mkIf (isRouter || cfg.model != null) (let
      modelsPath =
        if isRouter
        then cfg.router.modelsDir
        else builtins.dirOf cfg.model;
    in ''
      mkdir -p "${modelsPath}"
      chown -R ${svcUser}:${svcGroup} "${modelsPath}" 2>/dev/null || true
    '');
  };
}
