{
  lib,
  mkDarwinPackage,
  raven,
}: let
  version = "0.1.0";
  bundleId = "com.ggr.raven-desktop";
  # Placeholder icon (a plain dark bird glyph, generated by make-icon.swift in
  # this directory — NOT the Raven project's artwork, no licence attached).
  # Lives beside the other icon assets in modules/overlays/. Overwrite that
  # file with a real icon and the next build picks it up.
  ravenIcon = ../../modules/overlays/raven-icon.icns;
in
  mkDarwinPackage rec {
    pname = "raven-desktop";
    inherit version;

    src = ./.;

    # Compile the AppKit + WKWebView wrapper with Xcode's swiftc directly
    # (xcrun wraps the toolchain in sandbox-exec, which fails inside the nix
    # sandbox — same reason as pkgs/photokit-export). -resource-dir is needed
    # so the stdlib is found without xcrun, and -sdk for the macOS SDK.
    # `${raven}` is substituted into the source so the app knows the exact
    # store path of the CLI it drives.
    installPhase = ''
      runHook preInstall

      TOOLCHAIN="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain"
      SWIFTC="$TOOLCHAIN/usr/bin/swiftc"
      RESDIR="$TOOLCHAIN/usr/lib/swift"
      SDKROOT="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
      # If MacOSX.sdk doesn't resolve, ask xcrun (rare).
      [ -d "$SDKROOT" ] || SDKROOT="$(/usr/bin/xcrun --sdk macosx --show-sdk-path 2>/dev/null)"

      APP="$out/Applications/Raven.app"
      mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

      WORKDIR="$TMPDIR/raven-desktop-build"
      mkdir -p "$WORKDIR/mc"
      cp "$src/raven-desktop.swift" "$WORKDIR/raven-desktop.swift"
      substituteInPlace "$WORKDIR/raven-desktop.swift" \
        --replace-fail "@RAVEN_BIN@" "${raven}/bin/raven" \
        --replace-fail "@PORT@" "18792"

      "$SWIFTC" -module-cache-path "$WORKDIR/mc" \
        -sdk "$SDKROOT" -resource-dir "$RESDIR" -O \
        -o "$APP/Contents/MacOS/raven-desktop" \
        "$WORKDIR/raven-desktop.swift"

      cp "${ravenIcon}" "$APP/Contents/Resources/raven.icns"

      cat > "$APP/Contents/Info.plist" <<'PLIST'
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
      <dict>
        <key>CFBundleDisplayName</key><string>Raven</string>
        <key>CFBundleExecutable</key><string>raven-desktop</string>
        <key>CFBundleIdentifier</key><string>${bundleId}</string>
        <key>CFBundleName</key><string>Raven</string>
        <key>CFBundleIconFile</key><string>raven.icns</string>
        <key>CFBundleShortVersionString</key><string>${version}</string>
        <key>CFBundleVersion</key><string>${version}</string>
        <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
        <key>CFBundlePackageType</key><string>APPL</string>
        <key>LSMinimumSystemVersion</key><string>12.0</string>
        <key>NSHighResolutionCapable</key><true/>
        <key>NSPrincipalClass</key><string>NSApplication</string>
      </dict>
      </plist>
      PLIST

      # Ad-hoc sign with a STABLE identifier, so the bundle has a signature and
      # a durable identity independent of its nix store path. mkDarwinPackage
      # keeps dontFixup/dontStrip on, which would otherwise invalidate it.
      /usr/bin/codesign -s - -f --identifier "${bundleId}" "$APP"

      runHook postInstall
    '';

    meta = {
      description = "Native macOS app wrapper for the Raven CLI agent (AppKit + WKWebView)";
      homepage = "https://github.com/EverMind-AI/Raven";
      # mkDarwinPackage defaults meta.license to mit; set it explicitly.
      license = lib.licenses.mit;
      platforms = ["aarch64-darwin"];
    };
  }
