{
  pkgs,
  pkgs-unstable,
  ...
}: {
  environment.systemPackages = with pkgs; [
    chromium
    pkgs-unstable.ghostty
    todoist
    todoist-electron
    gapless
    lollypop
    resonance
    spot
    tagger
    jujutsu
    delta
    karere
    pkgs-unstable.python312Packages.python-kasa
    uefitool
    gamescope
    yubioath-flutter
    coreutils
    kakoune
    resources
    keeweb
    amberol
    apostrophe
    dig
    nodejs
    gcc
    libreoffice
    mesa-demos
    newsflash
    libresprite
    pkgs-unstable.mailspring
    element-desktop
    age-plugin-yubikey
    passage
    rage
    distrobox
    monophony
    kdePackages.audiotube
    zenity
    libnotify
    linuxKernel.packages.linux_zen.xone
    localsend
    easyeffects
    noise-repellent
    cargo
    rust-script
    xclip
    rocmPackages.rocminfo
    usb-reset
    gimp
    krita
    glmark2
    radeontop
    nix-search-cli
    cpu-x
    bsd-finger
    foliate
    nms
    bc
    dconf-editor
    dconf2nix
    obs-studio
    usbview
    gsound
    libgda6
    gnomeExtensions.easyeffects-preset-selector
    gnomeExtensions.pano
    pkgs-unstable.gnomeExtensions.another-window-session-manager
    gnomeExtensions.dash-to-panel
    libsecret
    jless
    spotify
    discord
    slack
    signal-desktop
    gnome-tweaks
    wmctrl
    obsidian
    dwarf-fortress
    zoom-us
    desktop-file-utils
    rustc
    wget
    usbutils
    ulauncher
    tlp
    (python3.withPackages (pp: with pp; [python-kasa]))
  ];
}
