{
  description = "Scott Bonds <scott@ggr.com> multi-machine flake (darwin + NixOS)";
  inputs = {
    # ---- BEGIN nr-managed input pins ---------------------------------------------
    # Generated by `nr` (see .config/nix/nr-pins) — do not hand-edit this block.
    # Edit the registry at .config/nix/flake-pins.json instead.
    #
    # A pin freezes an input at the last rev that built, because that input's
    # branch head would need a package built from source whose own tests fail
    # here. `nr --update` probes every pin against its branch head before
    # updating (a whole-system `nix build --dry-run` with that input overridden)
    # and drops the pin as soon as a substituter carries the package again.
    #
    # nixpkgs — pinned 2026-10-09, normally nixos-26.05
    #   (thrift)
    #   the stable bump changed python3.13-tokenizers, so it stopped
    #   substituting; building it pulls its test deps (datasets, pyarrow,
    #   arrow-cpp) and thrift 0.24.0's C++ tests do not compile against
    #   libcxx 21 (a Catch2 static_assert plus an assembler error).
    nixpkgs.url = "github:NixOS/nixpkgs/774debe7a0d1b496e35677ad955a1011c6ff74f3";
    #
    # nixpkgs-unstable — pinned 2026-10-09, normally nixpkgs-unstable
    #   (anyio)
    #   it moved CPython to 3.12.15, which backports gh-156793 /
    #   CVE-2026-19553 (SSLContext.wrap_bio() rejects server_hostname in
    #   server mode); anyio 4.14.2's own pytest suite fails on it. Arrives
    #   through hermes-agent's python env.
    nixpkgs-unstable.url = "github:NixOS/nixpkgs/c9fe7d12cd78d1adcd12dd15e24432dde5b155a0";
    # ---- END nr-managed input pins -----------------------------------------------

    nix-darwin.url = "github:nix-darwin/nix-darwin/nix-darwin-26.05";
    nix-darwin.inputs.nixpkgs.follows = "nixpkgs";

    home-manager.url = "github:nix-community/home-manager/release-26.05";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";

    nix-index-database.url = "github:nix-community/nix-index-database";
    nix-index-database.inputs.nixpkgs.follows = "nixpkgs";
    vudials = {
      url = "github:bonds/nix-vudials";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    polyptych = {
      url = "github:bonds/polyptych";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    neocode = {
      url = "github:bonds/NeoCode";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    flake-parts.url = "github:hercules-ci/flake-parts";

    agenix = {
      url = "github:ryantm/agenix";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Hermes Agent (Nous Research) — home-manager module for accismus.
    # FOLLOWS nixpkgs-unstable on purpose (kept on an unstable channel: uv2nix
    # needs packages newer than stable 26.05 ships); unstable→unstable follows
    # is safe — the AGENTS.md gotcha is about following TO a stable channel.
    # Its electron-headers fetch is shimmed in
    # modules/packages/hermes-desktop-fixed.nix (drop with upstream PR #69458).
    hermes-agent.url = "git+https://github.com/NousResearch/hermes-agent?rev=749220ef0007f8d87bd1531f1c24b0fe93816385";
    hermes-agent.inputs.nixpkgs.follows = "nixpkgs-unstable";
    # Dedupe flake.lock's flake-parts_2 node: hermes-agent's flake-parts is only
    # another instance of the same input and follows ours fine. (Its
    # home-manager is NOT made to follow ours: hermes tracks nixpkgs-unstable,
    # our home-manager is release-26.05, and following to a stable channel can
    # break an unstable input — see the AGENTS.md follows gotcha.)
    hermes-agent.inputs.flake-parts.follows = "flake-parts";
  };
  outputs = inputs:
    inputs.flake-parts.lib.mkFlake {inherit inputs;} {
      imports = [./flake/default.nix];
    };
}
