# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" "sr_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/ce9f53ef-255d-4fa8-91b4-f5f845450fa8";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/C9D5-397C";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/27d85be6-facd-429f-a916-ca53e9a46f80";
    fsType = "ext4";
    neededForBoot = true;
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  boot.supportedFilesystems = ["zfs"];
  boot.zfs.devNodes = "/dev/disk/by-id";
  boot.zfs.extraPools = ["dragon"];

  boot.kernelParams = [
    "nvme_core.io_timeout=10"
    "nvme_core.max_retries=3"
    "zfs.zfs_deadman_failmode=wait"
    "panic=60"
    # Suppress harmless AER spam from Intel USB/PCIe root ports on console.
    "pci=noaer"
  ];

  systemd.settings.Manager = {
    RuntimeWatchdogSec = "30s";
    RebootWatchdogSec = "4min";
  };

  # Mitigation for CVE-2026-31431 (Copy Fail) — local privilege escalation via
  # authencesn not yet backported to 6.12.x. Remove when kernel >= 6.18.22.
  # https://mtlynch.io/claude-code-found-linux-vulnerability/
  boot.blacklistedKernelModules = ["authencesn"];
}
